---
ANSIBLE_HOME: "/export/home/mmuralikri/ansible4splunk/"
SPLUNK_USER: "splunk"
splunk_group: "splunk"
SPLUNK_HOME: "/opt/splunk"
SPLUNK_ETC: "{{SPLUNK_HOME}}/etc"
SPLUNK_APP_DEST: "{{SPLUNK_HOME}}/etc/apps/"
SPLUNK_DEPLOYMENT: "{{SPLUNK_ETC}}/deployment-apps"
SPLUNK_RELEASE_SLEEPTIME: "480"
SPLUNK_RELEASE_DEST: "{{SPLUNK_ETC}}/deployment-apps"
SPLUNK_BINARY: "{{ ANSIBLE_HOME }}/splunk_binary/splunk-6.6.3-e21ee54bc796-Linux-x86_64.tgz"
SPLUNK_VERSION: "6.6.2"
SPLUNK_LEGACY: "6.5.1"
splunklib_1_6_6_location: /opt/splunk
cluster_master: usmtnecdsplhf01
splunk_ca: 'cert.pem'
splunk_pem: 'server-key.pem'
splunk_authentication: 'authentication.conf'
splunk_authorize: 'authorize.conf'
SPLUNK_ADMIN: 'admin'
