---
SPLUNK_USER: "splunk"
splunk_group: "splunk"
SPLUNK_HOME: "/opt/splunk"
SPLUNK_ETC: "{{SPLUNK_HOME}}/etc"
SPLUNK_APP_DEST: "{{SPLUNK_HOME}}/etc/apps/"
SPLUNK_DEPLOYMENT: "{{SPLUNK_ETC}}/deployment-apps"
SPLUNK_RELEASE_SLEEPTIME: "480"
SPLUNK_RELEASE_DEST: "{{SPLUNK_ETC}}/deployment-apps"
SPLUNK_VERSION: "6.6.2"
SPLUNK_LEGACY: "6.5.1"
splunklib_1_6_2_location: /opt/splunk
cluster_master_usstl: usstl-splunk-cm01
cluster_master_gblo: uklon-splunk-cm01
cluster_master_cnhk: cnhkg-splunk-cm01
SPLUNK_ADMIN: 'admin'
syslog_ng_config_dir: "/etc/syslog-ng"
syslog_ng_user: syslog-ng
syslog_ng_config_default_port: 514