---
ANSIBLE_HOME: "/opt/splunk/ansible4splunk/"
splunk_user: "splunk"
splunk_group: "splunk"
SPLUNK_HOME: "/opt/splunk"
SPLUNK_ETC: "{{SPLUNK_HOME}}/etc"
SPLUNK_APP_DEST: "{{SPLUNK_HOME}}/etc/apps/"
SPLUNK_DEPLOYMENT: "{{SPLUNK_ETC}}/deployment-apps"
SPLUNK_RELEASE_SLEEPTIME: "480"
SPLUNK_RELEASE_DEST: "{{SPLUNK_ETC}}/deployment-apps"
SPLUNK_BINARY: "{{ ANSIBLE_HOME }}/splunk_binaries/splunk-6.6.2-4b804538c686-Linux-x86_64.tgz"
SPLUNK_VERSION: "6.6.2"
SPLUNK_LEGACY: "6.5.1"
splunk_new_password: ji395CaJ1cY5MXL
splunklib_1_6_6_location: /opt/splunk/support/bin
cluster_master: cluster-mster
cluster_secret: splunk123
indexer_discovery_secret: splunk12345
