- name: install cluster_slave_app
  copy:
    src: cluster_slave_app
    dest: "{{ SPLUNK_HOME }}/etc/apps"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: configure pass4SymmKey
  splunk_config_stanza:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    app: cluster_slave_app
    file: server
    stanza: clustering
    values:
        mode: slave
        pass4SymmKey: "{{ cluster_secret }}"
    splunklib: "{{ splunklib_1_6_6_location }}/splunklib-1.6.6"

- name: configure master_uri
  splunk_config_stanza:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    app: cluster_slave_app
    file: server
    stanza: clustering
    values:
        mode: slave
        master_uri: "https://{{ cluster_master }}:8089"
    splunklib: "{{ splunklib_1_6_6_location }}/splunklib-1.6.6"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"
