---

- name: unpack splunk.tar.gz

  unarchive:
    src: "{{ SPLUNK_BINARY }}"
    #dest is $SPLUNK_HOME/.., as the tarball contains splunk/ directory
    dest: "{{ SPLUNK_HOME }}/.."
    creates: "{{ SPLUNK_HOME }}/splunk-6.6.2-4b804538c686-Linux-x86_64-mainfest"