---
# Remove old tar backups from /opt/splunk/etc/
#
# USAGE:
# - include tasks: tasks/clean_local_sksh_apps.yml
#
- name: Removing pre-existing backup of local apps
  file:
    path=/opt/splunk/etc/apps-local.tar.gz state=absent

- name: Backing up local apps
  shell: tar -czf /opt/splunk/etc/apps-local.tar.gz /opt/splunk/etc/apps

  become: true
  become_user: "{{ splunk_user }}"
