- name: stop splunk
  command: /opt/splunk/bin/splunk stop
  become: true
  become_user: "{{ SPLUNK_USER }}"

  #Add a new task for removing all custom apps under /opt/splunk/etc/apps/

  # Add a task for removing indexes.conf in all indexers

- name: install cluster_peer_app
  copy:
    src: cluster_peer_app
    dest: "{{ SPLUNK_HOME }}/etc/apps"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: configure pass4SymmKey
  validate_certs: false
  splunk_config_stanza:
    auth_user: admin
    auth_password: "{{ splunk_new_password }}"
    app: cluster_peer_app
    file: server
    stanza: clustering
    values:
        mode: slave
        pass4SymmKey: "{{ cluster_secret }}"
        master_uri: "https://{{ cluster_master_cnhk }}:8089"
    splunklib: "{{ splunklib_1_6_6_location }}/splunklib-1.6.6"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=900 delay=30
  ignore_errors: yes
