#- name: create certs folder
#  tags:
#   - install
#   - security
#  file:
#    path=/opt/splunk/etc/auth/splunkweb
#    owner=splunk
#    group=splunk
#    mode=700
#    state=directory
#  become: true
#  become_user: "{{ SPLUNK_USER }}"

#- name: copy splunkkey.key
#  tags:
#   - install
#   - security
#  copy:
#    src=splunk_creds/{{ ansible_hostname }}/{{ splunk_ca }}
#    dest=/opt/splunk/etc/auth/splunkweb
#    owner=splunk
#    group=splunk
#    mode=700
#  become: true
#  become_user: "{{ SPLUNK_USER }}"

#- name: copy server-key.pem
#  tags:
#   - install
#   - security
#  copy:
#    src=splunk_creds/{{ ansible_hostname }}/{{ splunk_ca }}
#    dest=/opt/splunk/etc/auth/splunkweb
#    owner=splunk
#    group=splunk
#    mode=700
#  become: true
#  become_user: "{{ SPLUNK_USER }}"

- name: copy authorize.conf
  tags:
    - install
    - security
  copy:
    src=opt/splunk/etc/system/local/authorize.conf
    dest=/opt/splunk/etc/system/local
    owner=splunk
    group=splunk
    mode=700
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: copy authentication.conf
  tags:
    - install
    - security
  copy:
    src=opt/splunk/etc/system/local/authentication.conf
    dest=/opt/splunk/etc/system/local
    owner=splunk
    group=splunk
    mode=700
  notify: restart splunk
  become: true
  become_user: "{{ SPLUNK_USER }}"
