- name: stop splunk
  command: /opt/splunk/bin/splunk stop
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: removing pre-existing backup of local apps
  file:
    path=/opt/splunk/etc/apps-local.tar.gz state=absent
  ignore_errors: yes
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: backing up local apps
  shell: tar -czf /opt/splunk/etc/apps-local.tar.gz /opt/splunk/etc/apps
  ignore_errors: yes
  become: true
  become_user: "{{ splunk_user }}"

# Added a new task for removing all custom apps under /opt/splunk/etc/apps/
- name: remove all custom apps in the existing indexers
  file:
    state: absent
    path: "/opt/splunk/etc/apps/{{ item }}"
  with_items:
  - all_deploymentclients
  - emr_all_indexers_base
  - forwarder_inputs_app
  - global_citrix2003_inputs
  - global_citrix2008_inputs
  - global_misc_props
  - global_unix_inputs
  - isamonitor
  - Splunk_CiscoISE
  - Splunk_TA_BIT9-CarbonBlack
  - Splunk_TA_bro_json
  - Splunk_TA_bro_props
  - Splunk_TA_cisco-esa
  - Splunk_TA_windows_props
  - SSL-versions
  - TA-cisco-asa
  - TA-Damballa-Failsafe-520-v101
  - TA-DNSServer-NT6
  - TA-DomainController-NT6
  - TA-sepapp11
  - TA-sepapp12
  - Splunk_TA_paloalto
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: backing up indexes.conf,distsearch.conf and deploymentclient.conf
  command: cp /opt/splunk/etc/system/local/{{ item }} /tmp/
  with_items:
  - indexes.conf
  - deploymentclient.conf
  - distsearch.conf
  ignore_errors: yes
  become: true
  become_user: "{{ SPLUNK_USER }}"

# removing indexes.conf in all indexers
- name: remove indexes.conf and deploymentclient.conf
  file:
    state: absent
    path: "/opt/splunk/etc/system/local/{{ item }}"
  with_items:
  - indexes.conf
  - deploymentclient.conf
  ignore_errors: yes
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: install cluster_peer_app
  copy:
    src: cluster_peer_app
    dest: "{{ SPLUNK_HOME }}/etc/apps"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: restart splunk
  command: "{{ SPLUNK_HOME }}/bin/splunk restart"
  become: true
  become_user: "{{ SPLUNK_USER }}"

- name: Wait for Splunk startup
  wait_for: port=8089 timeout=30
  ignore_errors: yes
